intrinsics_data_root: "/home/ubuntu/Desktop/tsdf-fusion-python/data2/DESK/"
rgb_data_root: "/home/ubuntu/Desktop/tsdf-fusion-python/data2/DESK/color/"
depth_data_root: "/home/ubuntu/Desktop/tsdf-fusion-python/data2/DESK/depth/"
n_imgs: 900
voxel_size: 0.03
vol_bounds: [-1.0, 3.5, -3.0, 1.0, -0.5, 2.5]
n_samples: 196
deepth_scale: 1000.0